### PR TITLE
Support New commands rosenv & Use Cyclone DDS as default

### PR DESCRIPTION
**Pull request by evshary**
@QQting  Please help me to review the PR.

### CODE REVIEW

**Comment by QQting** [comment]
@evshary 
There are conflicting files. 
I've tested it, when I use dashing, I don't know why `$RMW_IMPLEMENTATION` is empty. And I think **ROS codename** should reuse `$ROS_DISTRO`

**Comment by evshary** [comment]
> @evshary
> There are conflicting files.
> I've tested it, when I use dashing, I don't know why `$RMW_IMPLEMENTATION` is empty. And I think **ROS codename** should reuse `$ROS_DISTRO`

Well, it's already outdated. I'll update it later.

**Comment by evshary** [comment]
@QQting  I've updated it.

**Comment by QQting** [comment]
Hi @evshary ,
$RMW_IMPLEMENTATION is still empty, is it normal?
ros@rostest:~/ros_menu$ ros_menu_env 
* ROS_DISTRO=dashing
* ROS_DOMAIN_ID=30
* RMW_IMPLEMENTATION=
* CYCLONEDDS_URI=
* Workspace Layer:
  - /opt/ros/dashing

**Pull request merged**
