### PR TITLE
Support running bridge automatically.

### PR DESCRIPTION
**Pull request by evshary**
* Support running bridge
* Rename CycloneDDS to Eclipse Cyclone DDS

### CODE REVIEW

**Comment by evshary** [comment]
@QQting  Can you help me to review the changes?

**Comment by QQting** [comment]
What if package 'ros1_bridge' is not found in users' ROS 2 env? Shall we help users to install them? Or we can just suggest which command to run installation.

**Comment by evshary** [comment]
> What if package 'ros1_bridge' is not found in users' ROS 2 env? Shall we help users to install them? Or we can just suggest which command to run installation.

I think suggestion is better. I'll update the PR.

**Comment by evshary** [comment]
@QQting  Done. I'll ask users to install ros1_bridge while not installed.

**Comment by QQting** [comment]
@evshary I've tried auto-bridge, it's good! 
How about checking whether CycloneDDS is installed when users choose this DDS?

**Comment by evshary** [comment]
> How about checking whether CycloneDDS is installed when users choose this DDS?

OK. I've added it.

**Pull request merged**
